#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_TILE 30

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_LIMIT_OBJ 1

// From 2: Enemies
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_PARAGOOMBA	3
#define OBJECT_TYPE_KOOPA	4
#define OBJECT_TYPE_RED_KOOPA 5
#define OBJECT_TYPE_PARAKOOPA 6
#define OBJECT_TYPE_PIRANHA 7
#define OBJECT_TYPE_VENUS 8
#define OBJECT_TYPE_RED_VENUS 9

// From 20: Collectible
#define OBJECT_TYPE_COIN 20

// From 30: Static
#define OBJECT_TYPE_PLATFORM 30
#define OBJECT_TYPE_TUNNEL 31
#define OBJECT_TYPE_FULL_PLATFORM 32
#define OBJECT_TYPE_WALL 33
#define OBJECT_TYPE_PLANT_TUNNEL 34
#define OBJECT_TYPE_NO_COLLIDE_PLATFORM 35
#define OBJECT_TYPE_NO_COLLIDE_WALL 36
#define OBJECT_TYPE_ONLY_MARIO_COLLIDE_WALL 37

//From 40: Block
#define OBJECT_TYPE_BRICK 40

#define OBJECT_TYPE_PORTAL	50

#define OBJECT_TYPE_BLOCK 60
#define OBJECT_TYPE_QUESTION_BLOCK 61

#define OBJECT_TYPE_BACKGROUND 100

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 



#define ID_SPRITE_GOOMBA 20000

#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_PARA_GOOMBA_WING (ID_SPRITE_GOOMBA + 1100)
#define ID_SPRITE_PARA_GOOMBA_NO_WING (ID_SPRITE_GOOMBA + 1200)

#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)
#define ID_SPRITE_PARA_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2100)

#define ID_SPRITE_GOOMBA_DIE_UPSIDE_DOWN (ID_SPRITE_GOOMBA + 3000)
#define ID_SPRITE_PARA_GOOMBA_DIE_UPSIDE_DOWN (ID_SPRITE_GOOMBA + 3100)

#define ID_SPRITE_PARA_GOOMBA_FLY (ID_SPRITE_GOOMBA + 4100)

#define ID_SPRITE_PLANT 30000
#define ID_SPRITE_PIRANHA (ID_SPRITE_PLANT + 1000)
#define ID_SPRITE_VENUS_LEFT_UP (ID_SPRITE_PLANT + 2000)
#define ID_SPRITE_VENUS_LEFT_DOWN (ID_SPRITE_PLANT + 3000)
#define ID_SPRITE_VENUS_RIGHT_UP (ID_SPRITE_PLANT + 4000)
#define ID_SPRITE_VENUS_RIGHT_DOWN (ID_SPRITE_PLANT + 5000)
#define ID_SPRITE_RED_VENUS_LEFT_UP (ID_SPRITE_PLANT + 2100)
#define ID_SPRITE_RED_VENUS_LEFT_DOWN (ID_SPRITE_PLANT + 3100)
#define ID_SPRITE_RED_VENUS_RIGHT_UP (ID_SPRITE_PLANT + 4100)
#define ID_SPRITE_RED_VENUS_RIGHT_DOWN (ID_SPRITE_PLANT + 5100)
#define ID_SPRITE_FIRE_BALL (ID_SPRITE_PLANT + 6000)

#define ID_SPRITE_KOOPA 40000
#define ID_SPRITE_KOOPA_WALK (ID_SPRITE_KOOPA + 1000)
#define ID_SPRITE_KOOPA_WALK_RIGHT (ID_SPRITE_KOOPA + 2000)
#define ID_SPRITE_RED_KOOPA_WALK (ID_SPRITE_KOOPA + 1100)
#define ID_SPRITE_RED_KOOPA_WALK_RIGHT (ID_SPRITE_KOOPA + 2100)
#define ID_SPRITE_PARA_KOOPA_WALK (ID_SPRITE_KOOPA + 1200)
#define ID_SPRITE_PARA_KOOPA_WALK_RIGHT (ID_SPRITE_KOOPA + 2200)

#define ID_SPRITE_KOOPA_DEFEND (ID_SPRITE_KOOPA + 3000)
#define ID_SPRITE_KOOPA_RECOVER (ID_SPRITE_KOOPA + 4000)
#define ID_SPRITE_RED_KOOPA_DEFEND (ID_SPRITE_KOOPA + 3100)
#define ID_SPRITE_RED_KOOPA_RECOVER (ID_SPRITE_KOOPA + 4100)

#define ID_SPRITE_KOOPA_DEFEND_UPSIDE_DOWN (ID_SPRITE_KOOPA + 5000)
#define ID_SPRITE_KOOPA_RECOVER_UPSIDE_DOWN (ID_SPRITE_KOOPA + 6000)
#define ID_SPRITE_RED_KOOPA_DEFEND_UPSIDE_DOWN (ID_SPRITE_KOOPA + 5100)
#define ID_SPRITE_RED_KOOPA_RECOVER_UPSIDE_DOWN (ID_SPRITE_KOOPA + 6100)

//From 7: Collectible
#define ID_SPRITE_COIN 70000


//From 8: Blocks
#define ID_SPRITE_BRICK 80000
#define ID_SPRITE_EMPTY_BLOCK (ID_SPRITE_BRICK + 1000)
#define ID_SPRITE_QUESTION_BLOCK (ID_SPRITE_BRICK + 2000)

//From 9: Static
#define ID_SPRITE_CLOUD 90000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+100)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+200)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+300)

#define ID_SPRITE_TUNNEL 91000
#define ID_SPRITE_TUNNEL_BEGIN (ID_SPRITE_TUNNEL+100)
#define ID_SPRITE_TUNNEL_MIDDLE (ID_SPRITE_TUNNEL+200)
#define ID_SPRITE_TUNNEL_END (ID_SPRITE_TUNNEL+300)

#define ID_SPRITE_PLAIN 92000
#define ID_SPRITE_PLAIN_WORLD_1 (ID_SPRITE_PLAIN+100) //1->3 top, 4->6 mid, 7->9 bot

#define ID_SPRITE_SEMI_SOLID 93000
#define ID_SPRITE_SEMI_SOLID_WHITE (ID_SPRITE_SEMI_SOLID+100) //1->3 top, 4->6 mid, 7->9 bot
#define ID_SPRITE_SEMI_SOLID_GREEN (ID_SPRITE_SEMI_SOLID+200) //1->3 top, 4->6 mid, 7->9 bot
#define ID_SPRITE_SEMI_SOLID_PINK (ID_SPRITE_SEMI_SOLID+300) //1->3 top, 4->6 mid, 7->9 bot
#define ID_SPRITE_SEMI_SOLID_BLUE (ID_SPRITE_SEMI_SOLID+400) //1->3 top, 4->6 mid, 7->9 bot
#define ID_SPRITE_SEMI_SOLID_SHADOW (ID_SPRITE_SEMI_SOLID+500) //1->3 vertical, 4-5 horizontal

//From 20: Background
#define ID_SPRITE_BG_WORLD_1_1 200000