#pragma once
#include "GameObject.h"
#include "MarioForm.h"

// SMALL MARIO


#define ID_ANI_MARIO_SMALL_IDLE_RIGHT 1100
#define ID_ANI_MARIO_SMALL_IDLE_LEFT 1102
#define ID_ANI_MARIO_SMALL_PIPE 1103

#define ID_ANI_MARIO_SMALL_WALKING_RIGHT 1200
#define ID_ANI_MARIO_SMALL_WALKING_LEFT 1201

#define ID_ANI_MARIO_SMALL_RUNNING_RIGHT 1300
#define ID_ANI_MARIO_SMALL_RUNNING_LEFT 1301

#define ID_ANI_MARIO_SMALL_BRACE_RIGHT 1400
#define ID_ANI_MARIO_SMALL_BRACE_LEFT 1401

#define ID_ANI_MARIO_SMALL_JUMP_WALK_RIGHT 1500
#define ID_ANI_MARIO_SMALL_JUMP_WALK_LEFT 1501

#define ID_ANI_MARIO_SMALL_JUMP_RUN_RIGHT 1600
#define ID_ANI_MARIO_SMALL_JUMP_RUN_LEFT 1601

#define ID_ANI_MARIO_SMALL_FULL_POWER_JUMP_LEFT 1801
#define ID_ANI_MARIO_SMALL_FULL_POWER_JUMP_RIGHT 1800

#define ID_ANI_SMALL_FULL_POWER_RUN_LEFT 1701
#define ID_ANI_SMALL_FULL_POWER_RUN_RIGHT 1700


#define ID_ANI_MARIO_SMALL_IDLE_HOLDING_RIGHT 1150
#define ID_ANI_MARIO_SMALL_IDLE_HOLDING_LEFT 1151

#define ID_ANI_MARIO_SMALL_WALKING_HOLDING_RIGHT 1250
#define ID_ANI_MARIO_SMALL_WALKING_HOLDING_LEFT 1251

#define ID_ANI_MARIO_SMALL_RUNNING_HOLDING_RIGHT 1350
#define ID_ANI_MARIO_SMALL_RUNNING_HOLDING_LEFT 1351

#define ID_ANI_MARIO_SMALL_FULL_POWER_JUMP_HOLDING_LEFT 1851
#define ID_ANI_MARIO_SMALL_FULL_POWER_JUMP_HOLDING_RIGHT 1850

#define ID_ANI_MARIO_SMALL_JUMP_HOLDING_RIGHT 1550
#define ID_ANI_MARIO_SMALL_JUMP_HOLDING_LEFT 1551

#pragma endregion

#define GROUND_Y 160.0f

#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2

#define MARIO_SIT_HEIGHT_ADJUST ((MARIO_BIG_BBOX_HEIGHT-MARIO_BIG_SITTING_BBOX_HEIGHT)/2)

#define MARIO_SMALL_BBOX_WIDTH  13
#define MARIO_SMALL_BBOX_HEIGHT 12

#define MARIO_SMALL_HOLD_OFFSET_X 10
#define MARIO_SMALL_HOLD_OFFSET_Y 3

class CMario;

class CMarioSmall : public CMarioForm
{
public:
	void Update(DWORD dt, CMario* mario, vector<LPGAMEOBJECT>* coObjects);
	int GetAniId(CMario* mario);
	void SetState(int state, CMario* mario);
	void GetBoundingBox(float& left, float& top, float& right, float& bottom, CMario* mario);
	int GetLevel() const;
	int GetUpStateChangeTime() { return 0; }
	void GetHoldOffset(float& ox, float& oy) { ox = MARIO_SMALL_HOLD_OFFSET_X; oy = MARIO_SMALL_HOLD_OFFSET_Y; }
	void OnTakeDamage(CMario* mario);
};
